"""highuvlith: lithography simulation from VUV (157/126 nm) through DUV
heritage lines, EUV (13.5 nm) and BEUV (6.7 nm) to soft/hard X-ray, with
pluggable illumination sources and optical systems backed by a Rust physics
engine (``highuvlith._native``).

Every capability is graded in docs/capability-matrix.md (✅ implemented,
🔶 simplified, 🧪 theoretical); result objects of simplified or theoretical
models carry ``.status`` and ``.notes``.
"""

from highuvlith._native import (
    SourceConfig,
    OpticsConfig,
    MaskConfig,
    ResistConfig,
    FilmStackConfig,
    ProcessConfig,
    GridConfig,
    SimulationEngine,
    AerialImageResult,
    ResistProfileResult,
    BatchSimulator,
    ProcessWindowResult,
    # MNSL classes
    PyMnslConfig as MnslConfig,
    PyMnslEngine as MnslEngine,
    PyMnslResult as MnslResult,
    PyNanosphereArrayConfig as NanosphereArrayConfig,
    PySpherePacking as SpherePacking,
    PySubstrateCoupling as SubstrateCoupling,
    py_simulate_moire_emission,
    # Volumetric / deep-layer classes and helpers
    VolumetricResult,
    HeightMapResult,
    LigaResult,
    LevelSetResult,
    CarPebResult,
    TalbotResult,
    EuvIlResult,
    develop_fast_marching,
    development_rate,
    height_map_from_times,
    grayscale_height_map,
    grayscale_transmittance_for_target,
    blazed_grating,
    microlens_array,
    # X-ray materials / LIGA diffraction
    LigaEdgeProfile,
    MultilayerMirror,
    tune_multilayer_period,
    xray_optical_constants,
    refractive_index,
    material_names,
    # Vector (polarized) pupil
    VectorSettings,
    vector_pupil_field,
    vector_pupil_map,
    radiometric_factor,
    fresnel_coefficients,
    # Optimization / patterning
    IltResult,
    OpcResult,
    SrafResult,
    DofComparison,
    SpacerPatterningResult,
    LeleResult,
    DsaResult,
    dose_to_size_threshold,
    simulate_lele,
    simulate_dsa,
    dsa_confined_lamellae,
    # Stochastics
    LerResult,
    compute_ler_lwr,
    photons_per_square,
    relative_shot_noise,
    resist_absorbed_fraction,
    # Quantum (N-photon) research module
    TwoBeamNPhoton,
    NoonImageResult,
    n_photon_absorption_image,
    quantum_flux_budget,
    quantum_aerial_image,
)

from highuvlith.api import (
    FullResult,
    simulate_line_space,
    simulate_contact_hole,
    sweep_focus,
    compare_illumination,
    IlluminationComparison,
    process_window,
    source_landscape,
    SourcePreset,
    wafer_throughput,
    expose_volumetric,
    simulate_liga,
    liga_edge_profile,
    simulate_interference,
    simulate_grayscale,
    simulate_quantum_line_space,
    simulate_volumetric,
    VolumetricProcessResult,
    develop_level_set,
    peb_gaussian,
    peb_car,
    simulate_talbot,
    simulate_euv_il,
    pupil_polarization_map,
    PupilPolarizationMap,
    vector_two_beam_contrast,
    contact_target,
    optimize_ilt,
    fragment_opc,
    insert_srafs,
    compare_sraf_dof,
    isolated_line_sraf_study,
    SrafStudy,
    sadp,
    saqp,
    GrayscaleResult,
    QuantumResult,
)

from highuvlith.mnsl import (
    MnslSimResult,
    simulate_moire_emission,
    create_nanosphere_array,
    sweep_rotation_angle,
    sweep_separation,
    optimize_moire_parameters,
)

__version__ = "0.2.0"

__all__ = [
    # Configuration
    "SourceConfig",
    "OpticsConfig",
    "MaskConfig",
    "ResistConfig",
    "FilmStackConfig",
    "ProcessConfig",
    "GridConfig",
    # Simulation
    "SimulationEngine",
    "BatchSimulator",
    # Results
    "AerialImageResult",
    "ResistProfileResult",
    "ProcessWindowResult",
    # High-level API
    "FullResult",
    "simulate_line_space",
    "simulate_contact_hole",
    "sweep_focus",
    "compare_illumination",
    "IlluminationComparison",
    "process_window",
    "source_landscape",
    "SourcePreset",
    "wafer_throughput",
    # Volumetric / deep-layer results
    "VolumetricResult",
    "HeightMapResult",
    "LigaResult",
    "LevelSetResult",
    "CarPebResult",
    "TalbotResult",
    "EuvIlResult",
    "VolumetricProcessResult",
    "GrayscaleResult",
    # Volumetric / deep-layer API
    "expose_volumetric",
    "develop_fast_marching",
    "develop_level_set",
    "development_rate",
    "peb_gaussian",
    "peb_car",
    "simulate_volumetric",
    "height_map_from_times",
    "simulate_liga",
    "liga_edge_profile",
    "simulate_interference",
    "simulate_grayscale",
    "simulate_talbot",
    "simulate_euv_il",
    "grayscale_height_map",
    "grayscale_transmittance_for_target",
    "blazed_grating",
    "microlens_array",
    # X-ray materials / LIGA diffraction
    "LigaEdgeProfile",
    "MultilayerMirror",
    "tune_multilayer_period",
    "xray_optical_constants",
    "refractive_index",
    "material_names",
    # Vector (polarized) imaging
    "VectorSettings",
    "pupil_polarization_map",
    "PupilPolarizationMap",
    "vector_two_beam_contrast",
    "vector_pupil_field",
    "vector_pupil_map",
    "radiometric_factor",
    "fresnel_coefficients",
    # Optimization / patterning
    "IltResult",
    "OpcResult",
    "SrafResult",
    "DofComparison",
    "SpacerPatterningResult",
    "LeleResult",
    "DsaResult",
    "SrafStudy",
    "contact_target",
    "optimize_ilt",
    "fragment_opc",
    "insert_srafs",
    "compare_sraf_dof",
    "isolated_line_sraf_study",
    "dose_to_size_threshold",
    "sadp",
    "saqp",
    "simulate_lele",
    "simulate_dsa",
    "dsa_confined_lamellae",
    # Stochastics
    "LerResult",
    "compute_ler_lwr",
    "photons_per_square",
    "relative_shot_noise",
    "resist_absorbed_fraction",
    # Quantum (N-photon) research module (🧪)
    "simulate_quantum_line_space",
    "QuantumResult",
    "TwoBeamNPhoton",
    "NoonImageResult",
    "n_photon_absorption_image",
    "quantum_flux_budget",
    "quantum_aerial_image",
    # MNSL Configuration
    "MnslConfig",
    "MnslEngine",
    "MnslResult",
    "NanosphereArrayConfig",
    "SpherePacking",
    "SubstrateCoupling",
    "py_simulate_moire_emission",
    # MNSL High-level API
    "MnslSimResult",
    "simulate_moire_emission",
    "create_nanosphere_array",
    "sweep_rotation_angle",
    "sweep_separation",
    "optimize_moire_parameters",
]
